---

- name: Set up bundlemanager tmpdir
  file: state=directory path=/var/run/bundlemanager/ owner=nobody group=nogroup

- name: Install Redis
  apt: pkg={{item}} state=installed
  with_items:
    - redis-server

- name: Ensure redis is running and enabled
  service: name=redis-server state=running enabled=yes

- name: Install Bundlemanager
  pip: name=bundlemanager version=1.0.1

- copy: src=bundlemanager.init dest=/etc/init.d/bundlemanager owner=root group=root

- name: Ensure bundlemanager is running and enabled
  service: name=bundlemanager state=running enabled=yes

- name: Configure bundlemanager
  template: src=bundlemanager.yaml.j2 dest=/etc/bundlemanager.yaml
  notify: reload bundlemanager

- wait_for: host=127.0.0.1 port={{bundlemanager_port}}
