---

- name: Install bundlemanager packages
  apt: pkg={{item}} state=installed
  with_items:
    - bundlemanager
    - redis-server

- name: Ensure redis is running and enabled
  service: name=redis-server state=running enabled=yes

- name: Ensure bundlemanager is running and enabled
  service: name=bundlemanager state=running enabled=yes

- name: Configure bundlemanager
  template: src=bundlemanager.yaml.j2 dest=/etc/bundlemanager.yaml
  notify: reload bundlemanager
