---

- name: cache config
  template: src=cache.config.tedge.j2 dest=/etc/trafficserver/cache.config owner={{ trafficserver_user }} group={{ trafficserver_group }}

- name: records config
  template: src=records.6.tedge.j2 dest=/etc/trafficserver/records.config owner={{ trafficserver_user }} group={{ trafficserver_group }}

- name: logging config
  template: src=logs_xml.config.j2 dest=/etc/trafficserver/logs_xml.config owner={{ trafficserver_user }} group={{ trafficserver_group }}

- name: remap dir
  file: state=directory path=/etc/trafficserver/remap.d/ owner={{trafficserver_user}} group={{trafficserver_group}}

- name: general remap config
  template: src=remap.conf.ddeflect.j2 dest=/etc/trafficserver/remap.config owner={{ trafficserver_user }} group={{ trafficserver_group }}

- name: remap config per-site
  template: src=remap.d.ddeflect.j2 dest=/etc/trafficserver/remap.d/{{item.key}}.config owner={{ trafficserver_user }} group={{ trafficserver_group }}
  with_dict: remap
  notify:
    - restart ats

- wait_for: host=0.0.0.0 port=80
- wait_for: host=0.0.0.0 port=443
