---
- name: Install ATS
  apt: pkg={{item}} state=installed
  with_items:
    - trafficserver
  tags: ats

- name: enable ATS init script
  file: src=trafficserver.default dest=/etc/default/trafficserver

- name: set up ATS service
  service: name=trafficserver state=started enabled=yes

- name: records config
  template: src=records.config.j2 dest=/etc/trafficserver/records.config owner=root group=root
  tags: ats

- name: logging config
  template: src=logs_xml.config.j2 dest=/etc/trafficserver/logs_xml.config owner=root group=root
  tags: ats

- name: remap config
  template: src=remap.conf.j2 dest=/etc/trafficserver/remap.config owner=root group=root
  notify:
    - restart ats
  tags: ats
