---
- name: Install ATS
  apt: pkg={{item}} state=installed
  with_items:
    - trafficserver
  tags: ats

- name: enable ATS init script
  file: src=trafficserver.default dest=/etc/default/trafficserver

- name: set up ATS service
  service: name=trafficserver state=started enabled=yes

- name: chown ATS directory
  file: path=/etc/trafficserver owner={{ trafficserver_user }} group={{ trafficserver_group }}

- include: config.yml
- include: ssl.yml
