---

- hosts: all
  user: root
  vars_files:
    - clients.yml
    - deflect.yml
  vars:
    locale: en_US.UTF-8
    timezone: UTC
  roles:
    - common

- hosts: distributed.deflect.ca
  user: root
  vars:
    network: distributed.deflect.ca
    originstring: distributed.deflect.ca
  roles:
    - trafficserver
    - edgecommon
    - bundlemanager
    #- botnetdbp
  vars_files:
    - deflect.yml
    - clients.yml
    - edges.yml

- hosts: controller
  sudo: True
  roles:
    - dns
  vars_files:
    - deflect.yml
    - clients.yml
