---

- hosts: all
  sudo: True
  vars_files:
    - clients.yml
    - deflect.yml
  vars:
    locale: en_US.UTF-8
    timezone: UTC
  roles:
    - common

- hosts: staging
  sudo: True
  vars:
    network: staging
    originstring: staging.deflect.ca
  roles:
    - trafficserver
    #- botnetdbp
  vars_files:
    - deflect.yml
    - clients.yml

- hosts: controller
  sudo: True
  roles:
    - dns
  vars_files:
    - deflect.yml
    - clients.yml
