---

- name: Install basic package requirements
  apt: pkg={{item}} state=installed
  with_items:
    - sudo
    - rsync
    - ntp
    - iftop
    - vim
    - emacs23-nox
    - tmux
    - screen
    - ntp

- name: Ensure ntpd is running and enabled
  service: name=ntp state=running enabled=yes

- name: set locale to {{ locale }}
  command: /usr/sbin/update-locale LANG={{ locale }} LC_ALL={{ locale }}

- name: set /etc/localtime to {{ timezone }}
  command: /bin/cp /usr/share/zoneinfo/{{ timezone }} /etc/localtime

- name: set /etc/timezone to {{ timezone }}
  template: src=timezone dest=/etc/timezone
  notify: update tzdata
