---

- name: Update Apt cache information
  apt: update_cache=yes

- name: Install basic package requirements
  apt: pkg={{item}} state=installed
  with_items:
    - sudo
    - rsync
    - ntp
    - iftop
    - python
    - curl
    - vim
    - emacs23-nox
    - tmux
    - screen
    - ntp
    - ca-certificates

- name: Ensure ntpd is running and enabled
  service: name=ntp state=running enabled=yes

- name: set locale to {{ locale }}
  locale_gen: name={{ locale }} state=present

- name: set /etc/localtime to {{ timezone }}
  command: /bin/cp /usr/share/zoneinfo/{{ timezone }} /etc/localtime

- name: set /etc/timezone to {{ timezone }}
  template: src=timezone dest=/etc/timezone
  notify: update tzdata
