---

- apt: update_cache=yes
  run_once: true

- name: Install basic package requirements
  apt: pkg={{item}} state=installed
  with_items:
    - sudo
    - rsync
    - ntp
    - iftop
    - python
    - curl
    - vim
    - emacs23-nox
    - tmux
    - screen
    - ntp
    - ufw
    - ca-certificates
    - psmisc

- copy: src=tmux.conf dest=/root/.tmux.conf

- name: Ensure ntpd is running and enabled
  service: name=ntp state=running enabled=yes

- name: set locale to {{ locale }}
  locale_gen: name={{ locale }} state=present

- name: set /etc/localtime to {{ timezone }}
  command: /bin/cp /usr/share/zoneinfo/{{ timezone }} /etc/localtime

- name: set /etc/timezone to {{ timezone }}
  template: src=timezone dest=/etc/timezone
  notify: update tzdata

#- include: ufw.yml
#  tags: ufw firewall
