---

- name: Install bind
  apt: pkg={{item}} state=installed
  with_items:
    - bind9

- name: bind config
  template: src=named.conf.options.j2 dest=/etc/bind/named.conf.options
  notify:
    - reload bind

#NOTE: inside the template we access "item.key" in order to access the
#domain we're working with. it's odd but it works.

- name: Set up zonefile tmpdir
  file: state=directory path=/var/tmp/ddeflect/ owner=root group=root

- name: Per-site zone files
  template: src=zone.j2 dest=/var/tmp/ddeflect/{{ item.key }}.zone owner=root group=bind
  with_dict: remap
  # lol YAML :( need to wrap this statement in quotes.
  when: "'site_as_origin' in item.value and not item.value['site_as_origin']"

- name: Central DNS zone files
  template: src=networkzone.j2 dest=/var/tmp/ddeflect/{{item}}.zone owner=root group=bind
  with_items: dnets

- name: Master zone file configuration
  template: src=named.conf.local.j2 dest=/etc/bind/named.conf.local owner=root group=bind
