---
- name: Update Apt cache information
  apt: update_cache=yes

- name: Install bind
  apt: pkg={{item}} state=installed
  with_items:
    - bind9
  tags: dns

- name: bind config
  template: src=named.conf.options.j2 dest=/etc/bind/named.conf.options
  notify:
    - reload bind

#NOTE: inside the template we access "item.key" in order to access the
#domain we're working with. it's odd but it works.
- name: Per-site zone files
  template: src=zone.j2 dest=/tmp/{{ item.key }}.zone owner=root group=root
  with_dict: remap
  tags: dns

- name: Central DNS zone files
  template: src=networkzone.j2 dest=/tmp/{{item}}.zone owner=root group=root
  with_items: dnets
  tags: dns
